[project]
name = "learn-robotics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.11"
dependencies = [
    
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "numpy>=2.2,<2.4",
    "torch",
    "gym-hil>=0.1.13",
    "labmaze>=1.0.6",
    "lerobot[hilserl,aloha]"
]

[tool.uv.sources]
torch = { path = "wheels/torch-2.7.1+cpu-cp313-cp313-manylinux_2_28_x86_64.whl" }
lerobot = { path = "wheels/lerobot-0.4.3-py3-none-any.whl" }
